BEGIN;

INSERT INTO blogful_articles
    (title, date_published, content)
VALUES
('Article 1', '2019-01-01 12:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut nunc fermentum, venenatis quam ac, pretium ipsum. Vestibulum luctus sollicitudin lacus, eget hendrerit neque aliquam eu. Sed nunc neque, semper ac lobortis sed, tempus quis orci. Phasellus eu ante gravida massa dictum tincidunt ut eget ipsum. Integer tempor ante at commodo malesuada. Nam non purus ac nibh rutrum auctor. Pellentesque vulputate ligula id felis pellentesque fringilla ut nec nunc. Nullam varius, lectus et venenatis dignissim, ante ex eleifend ex, et placerat nunc leo a nisi. In maximus ex tortor, non gravida libero finibus eu. Cras vulputate aliquet erat vitae pretium.'),
('Article 2', '2019-01-02 12:00:00', 'Pellentesque maximus ex ligula, sit amet convallis augue commodo eu. Nunc posuere vestibulum magna vitae pretium. Suspendisse risus turpis, consequat non feugiat id, convallis in tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam arcu metus, bibendum sed porttitor a, fermentum ac nulla. In sed ex tempus, feugiat magna at, varius quam. Fusce aliquam eros nec mauris condimentum ullamcorper.'), ('Article 3', '2019-01-03 12:00:00', 'Nullam a porttitor augue. Donec elementum sapien nec sem volutpat interdum. Praesent viverra vel orci quis maximus. Morbi eu sodales elit. Vivamus ultrices nibh lectus, eget luctus leo lobortis et. Donec ut mi convallis, finibus sem et, tincidunt massa. Nam sagittis risus quis elit varius iaculis. Nam viverra, magna eget pharetra molestie, diam ante tincidunt ipsum, quis semper velit dui sed enim. Aenean tincidunt ipsum ut urna lacinia, venenatis tincidunt mauris ullamcorper. Aliquam eu mauris pretium, fringilla nisl sed, porta turpis. Vivamus viverra leo arcu, eu pharetra velit sollicitudin ac.'), 
('Article 4', '2019-01-04 12:00:00', 'Aliquam tellus lacus, efficitur at sodales at, pharetra ac felis. Praesent accumsan, erat quis consequat faucibus, ipsum urna tempor urna, ac consectetur eros nunc nec lacus. Aliquam erat volutpat. Maecenas bibendum accumsan risus, ut tempus felis laoreet ac. In hac habitasse platea dictumst. Pellentesque molestie, tellus a malesuada porta, odio mauris euismod quam, eget ultricies est felis vitae mi. Fusce eget volutpat justo. Phasellus neque sem, interdum at tortor ac, vulputate ultrices lectus. Praesent porta, nunc eget tristique facilisis, eros mi ullamcorper ante, eget fringilla eros orci ac elit. Duis fringilla augue sit amet nisi placerat, vel porta ex malesuada. Mauris vitae tristique nisl. Etiam blandit turpis est, non ornare turpis auctor id. Cras magna tellus, congue non urna sed, rutrum porta magna. Nunc a diam vel nisl faucibus sodales. Morbi ullamcorper odio vitae orci tempor, nec ornare libero mollis. Mauris fringilla gravida dui vitae vestibulum.'), ('Article 5', '2019-01-05 12:00:00', 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam ac ante dictum, lobortis quam eu, gravida leo. Phasellus eget lacus eu augue scelerisque sagittis. Aliquam erat volutpat. Sed luctus tortor nec fermentum consequat. Etiam orci tellus, lobortis eget finibus auctor, gravida ultrices nibh. Nulla congue ut neque nec ullamcorper. Nulla commodo quam non nunc rutrum, et aliquam lacus iaculis.');

COMMIT;




